export var languages = [
  {englishName: 'Albanian', nativeName: 'Shqip'},
  {englishName: 'Arabic', nativeName: 'العربية'},
  {englishName: 'Armenian', nativeName: 'Հայերեն'},
  {englishName: 'Awadhi', nativeName: 'अवधी'},
  {englishName: 'Azerbaijani', nativeName: 'Azərbaycanca'},
  {englishName: 'Bashkir', nativeName: 'Башҡорт'},
  {englishName: 'Basque', nativeName: 'Euskara'},
  {englishName: 'Belarusian', nativeName: 'Беларуская'},
  {englishName: 'Bengali', nativeName: 'বাংলা'},
  {englishName: 'Bhojpuri', nativeName: 'भोजपुरी'},
  {englishName: 'Bosnian', nativeName: 'Bosanski'},
  {englishName: 'Brazilian Portuguese', nativeName: 'português brasileiro'},
  {englishName: 'Bulgarian', nativeName: 'български'},
  {englishName: 'Cantonese (Yue)', nativeName: '粵語'},
  {englishName: 'Catalan', nativeName: 'Català'},
  {englishName: 'Chhattisgarhi', nativeName: 'छत्तीसगढ़ी'},
  {englishName: 'Chinese', nativeName: '中文'},
  {englishName: 'Croatian', nativeName: 'Hrvatski'},
  {englishName: 'Czech', nativeName: 'Čeština'},
  {englishName: 'Danish', nativeName: 'Dansk'},
  {englishName: 'Dogri', nativeName: 'डोगरी'},
  {englishName: 'Dutch', nativeName: 'Nederlands'},
  {englishName: 'English', nativeName: 'English'},
  {englishName: 'Estonian', nativeName: 'Eesti'},
  {englishName: 'Faroese', nativeName: 'Føroyskt'},
  {englishName: 'Finnish', nativeName: 'Suomi'},
  {englishName: 'French', nativeName: 'Français'},
  {englishName: 'Galician', nativeName: 'Galego'},
  {englishName: 'Georgian', nativeName: 'ქართული'},
  {englishName: 'German', nativeName: 'Deutsch'},
  {englishName: 'Greek', nativeName: 'Ελληνικά'},
  {englishName: 'Gujarati', nativeName: 'ગુજરાતી'},
  {englishName: 'Haryanvi', nativeName: 'हरियाणवी'},
  {englishName: 'Hindi', nativeName: 'हिंदी'},
  {englishName: 'Hungarian', nativeName: 'Magyar'},
  {englishName: 'Indonesian', nativeName: 'Bahasa Indonesia'},
  {englishName: 'Irish', nativeName: 'Gaeilge'},
  {englishName: 'Italian', nativeName: 'Italiano'},
  {englishName: 'Japanese', nativeName: '日本語'},
  {englishName: 'Javanese', nativeName: 'Basa Jawa'},
  {englishName: 'Kannada', nativeName: 'ಕನ್ನಡ'},
  {englishName: 'Kashmiri', nativeName: 'कश्मीरी'},
  {englishName: 'Kazakh', nativeName: 'Қазақша'},
  {englishName: 'Konkani', nativeName: 'कोंकणी'},
  {englishName: 'Korean', nativeName: '한국어'},
  {englishName: 'Kyrgyz', nativeName: 'Кыргызча'},
  {englishName: 'Latvian', nativeName: 'Latviešu'},
  {englishName: 'Lithuanian', nativeName: 'Lietuvių'},
  {englishName: 'Macedonian', nativeName: 'Македонски'},
  {englishName: 'Maithili', nativeName: 'मैथिली'},
  {englishName: 'Malay', nativeName: 'Bahasa Melayu'},
  {englishName: 'Maltese', nativeName: 'Malti'},
  {englishName: 'Mandarin', nativeName: '普通话'},
  {englishName: 'Mandarin Chinese', nativeName: '中文'},
  {englishName: 'Marathi', nativeName: 'मराठी'},
  {englishName: 'Marwari', nativeName: 'मारवाड़ी'},
  {englishName: 'Min Nan', nativeName: '閩南語'},
  {englishName: 'Moldovan', nativeName: 'Moldovenească'},
  {englishName: 'Mongolian', nativeName: 'Монгол'},
  {englishName: 'Montenegrin', nativeName: 'Crnogorski'},
  {englishName: 'Nepali', nativeName: 'नेपाली'},
  {englishName: 'Norwegian', nativeName: 'Norsk'},
  {englishName: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
  {englishName: 'Pashto', nativeName: 'پښتو'},
  {englishName: 'Persian (Farsi)', nativeName: 'فارسی'},
  {englishName: 'Polish', nativeName: 'Polski'},
  {englishName: 'Portuguese', nativeName: 'Português'},
  {englishName: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'},
  {englishName: 'Rajasthani', nativeName: 'राजस्थानी'},
  {englishName: 'Romanian', nativeName: 'Română'},
  {englishName: 'Russian', nativeName: 'Русский'},
  {englishName: 'Sanskrit', nativeName: 'संस्कृतम्'},
  {englishName: 'Santali', nativeName: 'संताली'},
  {englishName: 'Serbian', nativeName: 'Српски'},
  {englishName: 'Sindhi', nativeName: 'سنڌي'},
  {englishName: 'Sinhala', nativeName: 'සිංහල'},
  {englishName: 'Slovak', nativeName: 'Slovenčina'},
  {englishName: 'Slovene', nativeName: 'Slovenščina'},
  {englishName: 'Slovenian', nativeName: 'Slovenščina'},
  {englishName: 'Spanish', nativeName: 'Slovenščina'},
  {englishName: 'Swahili', nativeName: 'Slovenščina'},
  {englishName: 'Swedish', nativeName: 'Slovenščina'},
  {englishName: 'Tajik', nativeName: 'Slovenščina'},
  {englishName: 'Tamil', nativeName: 'Slovenščina'},
  {englishName: 'Tatar', nativeName: 'Slovenščina'},
  {englishName: 'Telugu', nativeName: 'Slovenščina'},
  {englishName: 'Thai', nativeName: 'Slovenščina'},
  {englishName: 'Turkish', nativeName: 'Slovenščina'},
  {englishName: 'Turkmen', nativeName: 'Slovenščina'},
  {englishName: 'Ukrainian', nativeName: 'Українська'},
  {englishName: 'Urdu', nativeName: 'اردو'},
  {englishName: 'Uzbek', nativeName: 'Ўзбек'},
  {englishName: 'Vietnamese', nativeName: 'Việt Nam'},
  {englishName: 'Welsh', nativeName: 'Cymraeg'},
  {englishName: 'Wu', nativeName: '吴语'},
];
